import { createFileRoute } from "@tanstack/react-router";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { CustomCursor } from "@/components/CustomCursor";
import { useLenis, useReveals } from "@/hooks/useScrollSetup";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | PowerTwinX" },
      { name: "description", content: "Privacy Policy for PowerTwinX." }
    ]
  }),
  component: PrivacyPage,
});

function Section({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <section className={`relative z-10 mx-auto w-full max-w-4xl px-6 py-20 md:py-32 ${className}`}>
      {children}
    </section>
  );
}

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center gap-2 rounded-full border border-border bg-surface/80 px-3 py-1 text-[11px] font-medium uppercase tracking-[0.18em] text-muted-foreground backdrop-blur">
      <span className="h-1.5 w-1.5 rounded-full bg-volt" />
      {children}
    </span>
  );
}

export function PrivacyPage() {
  useLenis();
  useReveals();

  return (
    <main className="relative min-h-screen flex flex-col overflow-clip bg-background font-sans">
      <CustomCursor />
      <Header />
      
      {/* Background Effect */}
      <div className="pointer-events-none absolute inset-0 z-0 grain opacity-[0.55]" />
      <div className="absolute top-0 left-0 w-full h-[50vh] bg-gradient-to-b from-volt/5 to-transparent pointer-events-none" />

      {/* Hero */}
      <Section className="mt-32 pb-4">
        <div className="reveal">
          <Eyebrow>Legal</Eyebrow>
          <h1 className="mt-6 text-5xl md:text-7xl font-light">
            Privacy <span className="text-gradient-volt font-medium">Policy</span>
          </h1>
          <p className="mt-6 text-xl text-muted-foreground leading-relaxed">
            Effective date: 2026-08-22
          </p>
          <div className="mt-8">
            <button 
              onClick={(e) => {
                e.preventDefault();
                document.getElementById('policy-content')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
              }}
              className="rounded-full bg-volt text-black px-8 py-3 text-sm font-medium shadow-[var(--shadow-soft)] hover:scale-105 transition-transform"
            >
              Read Now
            </button>
          </div>
        </div>
      </Section>

      <Section className="pt-4 flex-1">
        <div id="policy-content" className="reveal card-soft p-8 md:p-12 prose prose-invert max-w-none text-muted-foreground prose-headings:text-foreground prose-a:text-volt scroll-mt-32">
          <h2 className="text-2xl font-medium text-foreground mb-4">1. Introduction</h2>
          <p>Welcome to PowerTwinX</p>
          <p>PowerTwinX (“us”, “we”, or “our”) operates www.powertwinx.com (hereinafter referred to as “Service”).</p>
          <p>Our Privacy Policy governs your visit to www.powertwinx.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
          <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
          <p>Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">2. Definitions</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>SERVICE</strong> means the www.powertwinx.com website operated by PowerTwinX.</li>
            <li><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
            <li><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</li>
            <li><strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
            <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
            <li><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</li>
            <li><strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
          </ul>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">3. Information Collection and Use</h2>
          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">4. Information we collect</h2>
          <ol className="list-decimal pl-5 space-y-2">
            <li><strong>Contact information.</strong> We might collect your name, email, mobile number, phone number, street, city, state, pin code, financial and investment data, KYC details, country, IP address and such other data which helps us offer our products and services to the best of our ability.</li>
            <li><strong>Payment and billing information.</strong> We might collect your billing name, billing address and payment method when you register with us. We NEVER collect your credit card number or credit card expiry date or other details pertaining to your credit card on our website. Credit card information will be obtained and processed by our online payment partner.</li>
            <li><strong>Information you post.</strong> We collect information you post in a public space on our website or on a third-party social media site belonging to PowerTwinX.</li>
            <li><strong>Demographic information.</strong> We may collect demographic information about you, any other information provided by your during the use of our website. We might collect this as a part of a survey also.</li>
            <li><strong>Other information.</strong> If you use our website, we may collect information about your IP address and the browser you're using. We might look at what site you came from, duration of time spent on our website, pages accessed or what site you visit when you leave us. We might also collect the type of mobile device you are using, or the version of the operating system your computer or device is running.</li>
            <li>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, Permanent Account Number (or other taxpayer identification) number, office location and other data.</li>
          </ol>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">5. Collection of information in different ways</h2>
          <ol className="list-decimal pl-5 space-y-2">
            <li>We collect information directly from you. We collect information directly from you when you register with us. We also collect information if you post a comment on our websites or ask us a question through phone or email.</li>
            <li>We collect information from you passively. We use tracking tools like Google Analytics, Google Webmaster, browser cookies and web beacons for collecting information about your usage of our website.</li>
            <li>We get information about you from third parties. For example, if you use an integrated social media feature on our websites. The third-party social media site will give us certain information about you. This could include your name and email address.</li>
          </ol>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">6. Use of your personal information</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>to provide and maintain our Service;</li>
            <li>to notify you about changes to our Service;</li>
            <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
            <li>to provide customer support;</li>
            <li>to gather analysis or valuable information so that we can improve our Service;</li>
            <li>to monitor the usage of our Service;</li>
            <li>to detect, prevent and address technical issues;</li>
            <li>to fulfil any other purpose for which you provide it;</li>
            <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
            <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
            <li>We use information to contact you: We might use the information you provide to contact you for confirmation of a purchase on our website or for other promotional purposes.</li>
            <li>We use information to respond to your requests or questions. We might use your information to confirm your registration for an event or contest.</li>
            <li>We use information to improve our products and services. We might use your information to customize your experience with us. This could include displaying content based upon your preferences.</li>
            <li>We use information to look at site trends and customer interests. We may use your information to make our website and products better. We may combine information we get from you with information about you we get from third parties.</li>
            <li>We use information for security purposes. We may use information to protect our company, our customers, or our websites.</li>
            <li>We use information for marketing purposes. We might send you information about special promotions or offers. We might also tell you about new features or products. These might be our own offers or products, or third-party offers or products we think you might find interesting.</li>
            <li>We use information to send you transactional communications. We might send you emails or SMS about your account or a purchase.</li>
            <li>We use information as otherwise permitted by law.</li>
            <li>in any other way we may describe when you provide the information;</li>
            <li>for any other purpose with your consent.</li>
          </ul>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">7. Sharing of information with third-parties</h2>
          <ol className="list-decimal pl-5 space-y-2">
            <li>We will share information with third parties who perform services on our behalf. We share information with vendors who help us manage our online registration process or payment processors or transactional message processors. Some vendors may be located outside of India.</li>
            <li>We will share information with our business partners. This includes a third party who provide or service provider. Our partners use the information we give them as described in their privacy policies.</li>
            <li>We may share information if we think we have to in order to comply with the law or to protect ourselves. We will share information to respond to a court order or summon. We may also share it if a government agency or investigatory body requests. Or, we might also share information when we are investigating potential fraud. The only data we will share is the data we have access to, such as user name, address, nominee details, phone number and email address.</li>
            <li>We may share information with any successor to all or part of our business. For example, if part of our business is sold, we may give our customer list as part of that transaction.</li>
            <li>We may share your information for reasons not described in this policy. We will tell you before we do this.</li>
          </ol>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">8. Location Data</h2>
          <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.</p>
          <p>You can enable or disable location services when you use our Service at any time by way of your device settings.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">9. Retention of Data</h2>
          <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
          <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">10. Transfer of Data</h2>
          <p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
          <p>If you are located outside INDIA and choose to provide information to us, please note that we transfer the data, including Personal Data, to INDIA and process it there.</p>
          <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
          <p>PowerTwinX will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">11. Disclosure of Data</h2>
          <p>We may disclose personal information that we collect, or you provide:</p>
          <ol className="list-decimal pl-5 space-y-2">
            <li><strong>Disclosure for Law Enforcement.</strong> Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
            <li><strong>Business Transaction.</strong> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
            <li><strong>Other cases.</strong> We may disclose your information also: 
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>to our subsidiaries and affiliates;</li>
                <li>to contractors, service providers, and other third parties we use to support our business;</li>
                <li>to fulfill the purpose for which you provide it;</li>
                <li>for the purpose of including your company’s logo on our website;</li>
                <li>for any other purpose disclosed by us when you provide the information;</li>
                <li>with your consent in any other cases;</li>
                <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
              </ul>
            </li>
          </ol>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">12. Security of Data</h2>
          <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">13. Tracking Cookies Data</h2>
          <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
          <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
          <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
          <p>Examples of Cookies we use:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
            <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
          </ul>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">14. Your Data Protection Rights</h2>
          <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
          <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <strong>info@powertwinx.com</strong></p>
          <p>In certain circumstances, you have the following data protection rights:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>the right to access, update or to delete the information we have on you;</li>
            <li>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
            <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
            <li>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
            <li>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
            <li>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
          </ul>
          <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">15. Service Providers</h2>
          <p>We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
          <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">16. Analytics</h2>
          <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">17. CI/CD tools</h2>
          <p>We may use third-party Service Providers to automate the development process of our Service.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">18. Behavioral Remarketing</h2>
          <p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">19. Links to Other Sites</h2>
          <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">20. Email Opt-Out</h2>
          <p>You can opt out of receiving our marketing emails. To stop receiving our promotional emails, please click on the unsubscribe button and we will process your request within 7 days.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">21. Third party sites</h2>
          <p>If you click on one of the links to third party websites, you may be taken to websites we do not control. This policy does not apply to the privacy practices of those websites. Read the privacy policy of other websites carefully. We are not responsible for these third-party sites.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">22. Children’s Privacy</h2>
          <p>Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).</p>
          <p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">23. Changes to This Privacy Policy</h2>
          <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
          <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          <p>If you have any questions about this Policy or other privacy concerns, you can also email us at <strong>info@powertwinx.com</strong></p>

          <h2 className="text-2xl font-medium text-foreground mt-10 mb-4">Jurisdiction</h2>
          <p>If you choose to visit the website, your visit and any dispute over privacy is subject to this Policy and the website's terms of use. In addition to the foregoing, any disputes arising under this Policy shall be governed by the laws of India, State of Gujarat, City of Ahmedabad.</p>
        </div>
      </Section>

      <Footer />
    </main>
  );
}
